name=input('enter ur name:')
print(name)
birthyear=input('enter ur birthyear:')
print(birthyear)
type_of_input=type(birthyear)
print(type_of_input)
x=int(birthyear)
print(x)
y=type(x)
print(y)
